### ISSUE TITLE
Error after running "npm run start:dev" on a new project

### ISSUE THREAD

**Issue by magusfabius** [onflow/kitty-items#142]
**Describe the bug**
I just cloned the repository and followed step by step the installation of the documentation.

**To Reproduce**
clone repository, follow standard installation as described in the readme

**Expected behavior**

**Screenshots/Logs/Output**

npm run start:dev

> kitty-items@1.0.0 start:dev D:\dev\CRYPTO\kitty-items-master
> docker-compose --env-file .env.dev --profile dev up -d

Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'Impossibile trovare il file specificato.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 199, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'Impossibile trovare il file specificato.')
[17796] Failed to execute script docker-compose
←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcode←[0m ELIFECYCLE
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35msyscall←[0m spawn
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mfile←[0m C:\Program Files\git\bin\bash.exe
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35merrno←[0m ENOENT
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m kitty-items@1.0.0 start:dev: `docker-compose --env-file .env.dev --profile dev up -d`
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m spawn ENOENT
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m Failed at the kitty-items@1.0.0 start:dev script.
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m This is probably not a problem with npm. There is likely additional logging output above.
←[0m
←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m A complete log of this run can be found in:
←[0m←[37;40mnpm←[0m ←[0m←[31;40mERR!←[0m←[35m←[0m     C:\Users\fabio\AppData\Roaming\npm-cache\_logs\2021-09-22T08_54_15_520Z-debug.log
←[0m

**Environment (Optional - Version, OS, Browser, etc.)**
OS	        Microsoft Windows 10 Home
Version	10.0.19042 Build 19042

**Additional context (Optional - Anything else about the bug)**

**Comment by 10thfloor** [comment]
Kitty Items is not working under Windows at the moment.

**Comment by 10thfloor** [comment]
Closing in favour of https://github.com/onflow/kitty-items/issues/128

**Comment by magusfabius** [comment]
ok, so ubuntu? Cause I don't really wanna buy a mac ... or maybe yes?
