### ISSUE TITLE
Error in BaseEventHandler

### ISSUE THREAD

**Issue by andy-betin** [onflow/kitty-items#231]
Hello. Thanks for yours work.
**Describe the bug**
Last days got error in getting blocks :
Error retrieving events for block range fromBlock=61659507 toBlock=61659508 Error: 

    at Object.onEnd (/api/node_modules/@onflow/sdk/src/send/unary.js:18:18)

    at /api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24233

    at /api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11490

    at Array.forEach (<anonymous>)

    at e.rawOnError (/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11452)

    at e.onTransportHeaders (/api/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:9025)

    at NodeHttp.responseCallback (/api/node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:36:18)

    at Object.onceWrapper (events.js:520:26)

    at ClientRequest.emit (events.js:400:28)

    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)

**To Reproduce**
Jast start kitty-items

**Comment by MrDSGC** [comment]
Hi @andy-betin , try updating to the latest repo. Our recent update should address grpc issues.
