### ISSUE TITLE
Password authentication failed for user "kittyuser"

### ISSUE THREAD

**Issue by miaoqiz** [onflow/kitty-items#42]
Hi there,

Thanks so much for the excellent framework!

After deploying the contracts and following the API steps here:

https://github.com/onflow/kitty-items/tree/master/api#readme

There seems be an error with regard to password authentication failed for user "kittyuser". Please see the error below:

----------------------------------------

npm run start:dev

> kitty-items-api@0.0.1 start:dev
> tsnd --respawn src/index.ts

[INFO] 20:09:41 ts-nhttps://github.com/onflow/kitty-items/tree/master/api#readmeode-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)
error: password authentication failed for user "kittyuser"
    at Parser.parseErrorMessage (kitty-items/api/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (kitty-items/api/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (kitty-items/api/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (kitty-items/api/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 105,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '329',
  routine: 'auth_failed'
}

--------------------------------------------------------------------------------

Can you kindly advise how to fix it?

Thanks!

**Comment by miaoqiz** [comment]
Fixed it by re-opening the port. Thanks!
