### ISSUE TITLE
Cadence tests throws error

### ISSUE THREAD

**Issue by deivyd321** [onflow/kitty-items#44]
I have clean repository and I am trying to run command `go test` like this: `kitty-items\cadence\lib\go\test> go test`

But it throws this error: 
```
{"level":"debug","address":"f8d6e0586b0a20c7","contract":"FlowServiceAccount","contract_len":5100,"time":"2021-03-23T08:56:54+02:00","message":"a contract returned for f8d6e0586b0a20c7.FlowServiceAccount"}
{"level":"debug","address":"f8d6e0586b0a20c7","contract":"FlowStorageFees","contract_len":4689,"time":"2021-03-23T08:56:54+02:00","message":"a contract returned for f8d6e0586b0a20c7.FlowStorageFees"}--- FAIL: TestKibbleDeployment (0.09s)
panic: open ../../../cadence/kibble/contracts/Kibble.cdc: The system cannot find the path specified. [recovered]
        panic: open ../../../cadence/kibble/contracts/Kibble.cdc: The system cannot find the path specified.

goroutine 50 [running]:
testing.tRunner.func1.2(0x15b4d20, 0xc0002f7e90)
        C:/Program Files/Go/src/testing/testing.go:1144 +0x345
testing.tRunner.func1(0xc000055500)
        C:/Program Files/Go/src/testing/testing.go:1147 +0x4b6
panic(0x15b4d20, 0xc0002f7e90)
        C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/onflow/kitty-items/lib/go/test.readFile(0x16db0b5, 0x2c, 0x0, 0x0, 0x0)
        C:/Work/Rox/kitty-items/cadence/lib/go/test/test.go:101 +0x8d
github.com/onflow/kitty-items/lib/go/test.loadKibble(0x5054712f2f0ecf01, 0xc000209400, 0x18dc9c0, 0xc0001e5bc0)
        C:/Work/Rox/kitty-items/cadence/lib/go/test/kibble_test.go:273 +0x4f
github.com/onflow/kitty-items/lib/go/test.KibbleDeployContracts(0xc0002b01a0, 0xc000055500, 0x0, 0x0, 0x0, 0x0)
        C:/Work/Rox/kitty-items/cadence/lib/go/test/kibble_test.go:51 +0x23a
github.com/onflow/kitty-items/lib/go/test.TestKibbleDeployment(0xc000055500)
        C:/Work/Rox/kitty-items/cadence/lib/go/test/kibble_test.go:116 +0x70
testing.tRunner(0xc000055500, 0x181f448)
        C:/Program Files/Go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1239 +0x2b3
exit status 2
FAIL    github.com/onflow/kitty-items/lib/go/test       0.470s
```

Any suggestions how to fix it?

**Comment by 10thfloor** [comment]
Thanks for the issue!

**Comment by shubik22** [comment]
I don't believe the Cadence tests are in a functional state ATM.  A good start would be to modify the paths to point to the actual contracts (the paths are currently incorrect, which is why you're seeing that error @deivyd321).

@psiemens has a WIP PR to update the tests that might help as well: https://github.com/onflow/kitty-items/pull/33/files

**Comment by srinjoyc** [comment]
This should be fixed now in PR:https://github.com/onflow/kitty-items/pull/88 - please pull the new code and try again!
