### ISSUE TITLE
Running ./setup-minter.sh return error

### ISSUE THREAD

**Issue by balibou** [onflow/kitty-items#56]
When I run the script `./setup-minter.sh`, I get this error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:207:11)
    at /Users/benjamincherion/Desktop/kitty-items/api/node_modules/@onflow/send/src/send-transaction.js:8:39
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It sounds it is related to Buffer.from (and according to my quick researches the argument that is passed must be stringified)

**Comment by balibou** [comment]
solved when being on node v12.0.0 or higher (needed by @onflow/flow-js-sdk)
maybe it would be good to add a .nvm file with this version ?
