### ISSUE TITLE
The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object

### ISSUE THREAD

**Issue by kulame** [onflow/kitty-items#67]
hi
    i try to request a api server. but it return error.

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:206:11)
    at /srv/blockchain/kitty-items/api/node_modules/@onflow/send/src/send-transaction.js:8:39
    at process._tickCallback (internal/process/next_tick.js:68:7)
code.
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:206:11)
    at /srv/blockchain/kitty-items/api/node_modules/@onflow/send/src/send-transaction.js:8:39

this is the command what i used.

curl --request POST \
  --url http://localhost:3000/v1/kibbles/setup \
  --header 'Content-Type: application/json'

**Comment by kulame** [comment]
my npm version is 

➜  kitty-items git:(master) ✗ npm --version
6.14.4

**Comment by kulame** [comment]
i sloved this problem when i upgrade node version to v14.16.1
