### ISSUE TITLE
Error: Response closed without headers

### ISSUE THREAD

**Issue by MAkcanca** [onflow/kitty-items#76]
Following the getting started step by step, after I run npm run start:dev, I receive this console output
```
> kitty-items-api@0.0.1 start:dev /home/some/Projects/Personal/kitty-items/api
> tsnd --respawn src/index.ts --dev

[INFO] 18:39:54 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)
fetching latest block height
Listening on port 3000!
(node:18058) UnhandledPromiseRejectionWarning: Error: Response closed without headers
    at Object.onEnd (/home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/src/send/unary.js:15:18)
    at /home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24140
    at /home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11457
    at Array.forEach (<anonymous>)
    at e.rawOnError (/home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11419)
    at e.onTransportEnd (/home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:10289)
    at ClientRequest.<anonymous> (/home/some/Projects/Personal/kitty-items/api/node_modules/@onflow/sdk/node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:70:20)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Only thing I did differently was running npm audit fix after npm install. 
Possibly related to https://github.com/onflow/flow-js-sdk/issues/271

**Comment by ShikyC** [comment]
Same issue here. When deploying this repository to a new computer this error occurred. I think it's the latest commits causing this error because I have an old version of kitty-items running well on another machine.

**Comment by MAkcanca** [comment]
Not a solution yet, although I wonder if this is the right behaviour. On sdk/src/send/unary.js 
```
grpc.unary(method, {
      request: **request**,
      host: **host**,
      onEnd: ({ status, statusMessage, message }) => {
        if (status === grpc.Code.OK) {
          resolve(message)
        } else {
          reject(new Error(statusMessage))
        }
      },
    })
```

request comes as
```
{
  wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [ true ],
  pivot_: 1.7976931348623157e+308,
  convertedPrimitiveFields_: {}
}
```
and host comes as `undefined`. 🤔
