### ISSUE TITLE
Cannot find module '@onflow/sdk-resolve'

### ISSUE THREAD

**Issue by cybercent** [onflow/kitty-items#94]
```
cd api/
npm install
npm run start:dev
```

```
[ERROR] 18:12:36 Error: Cannot find module '@onflow/sdk-resolve'
```

**Comment by cybercent** [comment]
@10thfloor this issue appeared after the FCL upgrade.

Here is the stack trace I get when running `npm run start:dev` under `/api`
```js
[INFO] 18:38:02 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)
Error: Cannot find module '@onflow/sdk-resolve'
Require stack:
- /kitty-items/api/node_modules/@onflow/fcl/dist/fcl.js
- /kitty-items/api/src/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/kitty-items/api/node_modules/@onflow/fcl/dist/fcl.js:1:68)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._compile (/kitty-items/api/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.nodeDevHook [as .js] (/kitty-items/api/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:972:32)
[ERROR] 18:38:05 Error: Cannot find module '@onflow/sdk-resolve'
Require stack:
- /kitty-items/api/node_modules/@onflow/fcl/dist/fcl.js
- /kitty-items/api/src/index.ts
```

**Comment by 10thfloor** [comment]
@cybercent Did ou resolve this?

**Comment by 10thfloor** [comment]
We removed `@onflow/sdk` form this project so this is no longer an issue.
